#!/bin/bash
#x264 --bitrate $i --qp $(((i/200+3)*4)) -o 1 yuv/s-$j/1_192x144.yuv 


profile=("baseline" "main" "high" "high10" "high422" "high444")
preset=("ultrafast" "superfast" "veryfast" "faster" "fast" "medium" "slow")
tune=("film" "animation" "grain" "stillimage" "psnr" "ssim" "fastdecode" "zerolatency")
a=3
echo -n > 1.txt
for ((i=32;i>=16;i-=4));do
#for ((i=1000;i>=200;i-=200));do
	for ((j=30;j>=7;j/=2));do
		echo ==================encode $i-$j===================
		echo ==================encode $i-$j===================
		x264 --crf $i --profile ${profile[a]} -o 1 yuv/s-$j/1_192x144.yuv 
		x264 --crf $i --profile ${profile[a]} -o 2 yuv/x-$j/1_192x144.yuv 
		ls -l 1|sed 's/.*staff  //;s/ 11 21.*//' >> 1.txt
		ls -l 2|sed 's/.*staff  //;s/ 11 21.*//' >> 1.txt
	done
done
vim -e -s 1.txt -c"normal gg" -c "%normal 6J" -c "normal ZZ"
cat 1.txt|pbcopy
echo done
