#!/bin/bash
#############################################
# author:fang
# version : v1.0
# name  : xback
# dispcripe: backup files and dictory
# CopyRight@fangyunjiang[42550564@qq.com]
#############################################
source ~/command/common

_backup_path=~/.backup
_oper=0

function show_help()
{
	local -a list
	list="help"
	list=("${list[@]}" "Usage :xback [OPTIONS]")
	list=("${list[@]}" "  -l :show backfiles list")
	list=("${list[@]}" "  -h :show help ")
	__msgbox "${list[@]}"
}

function main()
{
	while getopts :lh opt;do
		_oper_right=1
		case $opt in
			l)_oper=1;;
			h)show_help;exit;;
			*)show_help;exit;;
		esac
	done

	[ $_oper_right -eq 0 ] && show_help && exit

	case $_oper in
		0)show_backlist;;
		1)show_backlist;;
	esac
}

main "$@"
