#!/usr/bin/env node

const word = process.argv[2];
const list = process.argv.slice(3);
if (!word) {
    console.log(list.join(' '));
} else {
    console.log(list.filter(o=>{
        let lastIndex = -1;
        let count = 0;
        for (const ch of word) {
            const index = o.indexOf(ch);
            if (index > lastIndex) {
                count++;
            }
            lastIndex = index;
        }
        return count === word.length;
    }).join(' '));
}
