#!/bin/bash
source ~/command/common

if __windows;then
    ip=$(node -e " \
    const os = require('os'); \
    const interfaces = os.networkInterfaces(); \
    let ip; \
    for (let devName in interfaces) { \
        var iface = interfaces[devName]; \
        for (var i = 0; i < iface.length; i++) { \
            var alias = iface[i]; \
            if (alias.family === 'IPv4' && alias.address !== '127.0.0.1' && !alias.internal) { \
                ip = alias.address; \
            } \
        } \
    } \
    console.log(ip)")
else
    ip=`ifconfig -a | grep -w inet | grep -v '127.0.0.1' | awk '{ print $2}'`
fi

if [ "$1" = "-h" ];then
  echo "xconfig -h|-i:show ip|-r:reset|default: modify config"
elif [ "$1" = "-i" ];then
  echo $ip
elif [ "$1" = "-r" ];then
  vim -e -s config.js -c ":%s/\(apiServer:.*\)\/\d\+\.\d\+\.\d\+\.\d\+:/\1\/localhost:/" -c ":wq"
  echo "set localhost done"
else
  vim -e -s config.js -c ":%s/\(apiServer:.*:\/\/\)\(\d\+\.\d\+\.\d\+\.\d\+:\)\|\(localhost:\)/\1${ip}:/" -c ":wq"
  echo "set $ip done"
fi
