#!/usr/bin/env node

const request = require('superagent');
const program = require('commander');
const _ = require('lodash');

program
.version('0.0.1')
.option('-u, --url [http://127.0.0.1:3000/test]', 'url of api')
.option('-d, --data <json>', 'data must be json format', (v)=>eval('v='+v), {})
.parse(process.argv);

const { url, data } = program;
request.get(url)
.query(data)
.end((error, res) => {
    if (error) {
        console.error('recv error:', error);
    } else {
        if (res.text) {
            console.log(res.text);
        } else if (_.size(res.body)) {
            console.log(res.body);
        } else {
            console.log(res.res.headers);
        }
    }
});
