#!/usr/local/bin/node
// var http = require('http');
var program = require('commander');
// var qs = require('querystring');

program
.version('0.0.1')
.option('-s, --host', 'server host', '127.0.0.1')
.option('-p, --port', 'server port', '3000')
.option('-t, --path', 'server get path', '/test')
.option('-u, --url', 'url=[host+\":\"+port+path], if use url, not set host etc.')
.option('-d, --data', 'data must be json format', '{}')
.parse(process.argv);

let { host, port, path, url, data } = program;
console.log({ host, port, path, url, data});

// var content = qs.stringify(data);

// var options = {
//     hostname: '127.0.0.1',
//     port: 8080,
//     path: '/login?' + content,
//     method: 'GET'
// };
//
// var req = http.request(options, function (res) {
//     // console.log('STATUS: ' + res.statusCode);
//     // console.log('HEADERS: ' + JSON.stringify(res.headers));
//     res.setEncoding('utf8');
//     res.on('data', function (chunk) {
//         console.log('recv: ', chunk);
//     });
// });
//
// req.on('error', function (e) {
//     console.log('error: ', e.message);
// });
//
// req.end();
