#!/bin/bash

source ~/command/common
ip="172.8.64.30"
password="feng+langma"
dir="$(date '+%Y%m%d')"
tmpfile=_xx_
_oper=0

function login_vi()
{
	expect -c "
		set timeout 60
		spawn ssh root@$ip;
		expect {
			\"*password:\" {send \"$password\r\"; exp_continue}
			\"*#\" {send \" cd /server/pes/log/$dir/\r __files=(\`ls\`)\r rm -f $tmpfile\r cp \$\a{__files\[\$\a{#__files\[@\]}-1\]} $tmpfile\r vi $tmpfile\r\"}
		}
		interact
	"
}

function login_cd_log()
{
	expect -c "
		set timeout 60
		spawn ssh root@$ip;
		expect {
			\"*password:\" {send \"$password\r\"; exp_continue}
			\"*#\" {send \" cd /server/pes/log/$dir/\r __files=(\`ls\`)\r file=\$\a{__files\[\$\a{#__files\[@\]}-1\]}\r\"}
		}
		interact
	"
}

function login()

{
	expect -c "
		set timeout 60
		spawn ssh root@$ip;
		expect {
			\"*password:\" {send \"$password\r\"; exp_continue}
			\"*#\" {send \" cd /server/pes\r\"}
		}
		interact
	"
}

function show_help()
{
	local -a list
	list="xhangzhou"
	list=("${list[@]}" "Usage :xhangzhou [-l|-v|-c|-h]")
	list=("${list[@]}" "pcs:login hangzhou and cd pes log dir")
	list=("${list[@]}" "pcs -l:cd /server/pes")
	list=("${list[@]}" "pcs -v:vi latest log")
	list=("${list[@]}" "pcs -c:cd latest log dir and set latest log file to file")
	list=("${list[@]}" "pcs -h:show help")
	__msgbox "${list[@]}"
}


function main()
{
	while getopts :lcvh opt;do
		case $opt in
			l)_oper=1;;
			c)_oper=1;;
			v)_oper=2;;
		*)show_help;exit;;
		esac
	done
	case $_oper in
		1)login;;
		0)login_cd_log;;
		2)login_vi;;
	esac
}

main "$@"

