#!/usr/bin/env node

const osHomedir = require('os-homedir');
const command = require('./js/command');
const path = require('path');
const fs = require('fs-extra');
const _ = require('lodash');
const shell = require('shelljs');
let code = [];

function clearCode() {
    code = [];
    this.prompt();
}
function showCode() {
    this.print(code.join('\n'));
    this.prompt();
}
function appendCode(line) {
    code.push(line);
    this.prompt();
}
function runCode() {
    this.prompt();
}
function showHelp () {
    this.print('commands:', 'blue');
    this.print('    <h|help>: show help');
    this.print('    <q|exit>: exit');
    this.print('    <c|clear>: 清除缓存的内容');
    this.print('    <s|show>: 显示缓存的内容');
    this.print('');
    this.prompt();
}
const COMMANDS = {
    'h|help': showHelp,
    'q|exit': function () { process.exit(0); },
    'c|clear': clearCode,
    's|show': showCode,
    'default': appendCode,
};

command(COMMANDS, { prompt: 'java' });
