#!/usr/local/bin/node
var fs = require("fs");
var rl = require('readline');
var path = require("path");

function getImageBase64(imagefile) {
    var extname = path.extname(imagefile);
    var basename = path.basename(imagefile);
    if ([".png", ".jpg", ".gif"].indexOf(extname) === -1) {
        console.log("imagefile must be png/jpg/gif file");
        process.exit();
    }
    var header = 'src="data:image/'+extname.substr(1)+';base64,'
    var imageBuf = fs.readFileSync(imagefile);
    return header+imageBuf.toString("base64")+'"';
}

var args = process.argv.slice(2), htmlfile, outputfile;
if (args.length < 2 || args[0] === '-h' || args[0] === '--help') {
    console.log("Usage:");
    console.log("base64 htmlfile outputfile");
    process.exit();
}
htmlfile = args[0];
outputfile = args[1];


var lineReader = rl.createInterface({
    input: fs.createReadStream(htmlfile)
});
lineReader.on('line', function (line) {
    if (/src="[^ ]*"/.test(line)) {
        var filename = line.replace(/.*src="([^"]*)".*/, '$1');
        if (!/^https?:\/\//.test(filename)) {
            line = line.replace(/src="[^ ]*"/, getImageBase64(filename));
        }
    }
    fs.appendFileSync(outputfile, line+'\n');
});
