#!/usr/bin/env node

// mysql> alter user 'root'@'localhost' identified with mysql_native_password by '123456';
// mysql> flush privileges;

const mysql = require('mysql2');
const moment = require('moment');
const command = require('./js/command');
const _ = require('lodash');
const DATA_BASE = 'db_smart_plate';
const CACHE = {};

let _prettyShell = true;
async function createMysql (commands, options) {
    const connection = mysql.createConnection({
        host: process.argv[2] || 'localhost',
        user: 'root',
        password: '123456',
        database: DATA_BASE,
    });
    const tables = await getTables(null, connection);
    let allFileds = [];
    for (const table of tables) {
        const fileds = await initFieldsOfTable(null, table, connection);
        allFileds = [...allFileds, ...fileds];
    }
    allFileds = _.uniq(allFileds);
    // 添加表，字段的自动完成
    function completer(line) {
        const words = line.replace(/\s,\s/g, ',').trimLeft().split(/\s/);
        const linePartial = _.last(_.last(words).split(','));
        let list = [];
        if (words.length <= 1) {
            list = ['select', 'update', 'delete'].filter((o) => o.startsWith(linePartial));
        } else {
            const preWord = _.toLower(_.nth(words, -2));
            if (_.includes(['from', 'update', 'into', 'ls', 's', 'm', 'r', 'c'], preWord)) {
                list = tables.filter((o) => o.startsWith(linePartial));
            }  else {
                const prePreWord = _.toLower(_.nth(words, -3));
                if (prePreWord === 's') {
                    const table = preWord;
                    const fileds = CACHE[table];
                    list = fileds.filter((o) => o.startsWith(linePartial));
                } else {
                    list = allFileds.filter((o) => o.startsWith(linePartial));
                }
            }
        }
        const found = list.filter((o) => o.startsWith(linePartial));
        return [found.length ? found : list, linePartial];
    }

    command(commands, { ...options, connection, completer });
}
async function format(self, line, connection) {
    const matches = line.match(/select(.*)from\s*(\w+)/);
    if (matches) {
        let list = matches[1].split(/,|\s/).filter(o=>o).join(',');
        const fields = await formatFields(this, matches[2], list, connection);
        line = line.replace(/select.*from/, `select ${fields} from`);
    }
    return line;
}
function formatResult(obj) {
    for (const key in obj) {
        const item = obj[key];
        if (item instanceof Buffer) {
            obj[key] = !!item.readInt8(0);
        } else if (item instanceof Date) {
            obj[key] = moment(item).format('YYYY-MM-DD HH:mm:ss');
        }
    }
    return obj;
}
async function formatFields(self, table, line, connection) {
    if (!line) {
        return '*';
    }
    let list = line.split(',');
    const allFields = getFieldsOfTable(table);
    list = list.map(o => new RegExp(o.replace('<', '^').replace('>', '$'), 'i'));

    return allFields.filter(o=>_.some(list, r=>r.test(o))).join(',');
}
async function getTables(self, connection) {
    if (!CACHE._tables) {
        CACHE._tables = (await querySQL(self, connection, 'show tables')).map(o=>o[_.keys(o)[0]]);
    }
    return CACHE._tables;
}
async function initFieldsOfTable(self, table, connection) {
    CACHE[table] = (await querySQL(self, connection, 'desc ' + table)).map(o=>o.Field);
    return CACHE[table];
}
function getFieldsOfTable(table) {
    if (!CACHE[table]) {
        return [];
    }
    return CACHE[table];
}
function querySQL(self, connection, query) {
    return new Promise(resolve=>{
        connection.query(query, (err, results) => {
            if (err) {
                if (self) {
                    self.error(err);
                    self.prompt();
                }
                resolve([]);
            } else {
                resolve(results);
            }
        });
    })
}
async function executeSQL(self, line, connection) {
    const results = await querySQL(self, connection, line);
    if (results.forEach) {
        results.forEach(o=>{
            self.showJson(formatResult(o), _prettyShell);
        });
    } else {
        self.showJson(results, _prettyShell);
    }
    self.prompt();
}
async function executeLine(line, { connection }) {
    if (!line) {
        return this.prompt();
    }
    line = await format(this, line, connection);
    await executeSQL(this, line, connection);
}
async function showTables(line, { connection }) {
    if (!line) { // show tables
        let results = await querySQL(this, connection, 'select database() as db');
        this.print('tables in '+ results[0].db +' :', 'red');
        results = await querySQL(this, connection, 'show tables');
        if (results) {
            this.print(_.map(results, o=>o[_.keys(o)[0]]).join('  '), 'green');
            this.prompt();
        }
    } else if (line === '-') { // show databases
        this.print('databases :', 'red');
        const results = await querySQL(this, connection, 'show databases');
        this.print(results.map(o=>o.Database).join('  '), 'green');
        this.prompt();
    } else { // show table fileds
        line = line.replace(/[^\w]*/g, '');
        const fileds = getFieldsOfTable(line);
        this.print(fileds.join('  '), 'green');
        this.prompt();
    }
}
function formatCond(line) {
    if (!line) {
        return '';
    }
    return 'WHERE ' + line
    .replace(/&/g, ' AND ')
    .replace(/\|/g, ' OR ')
    .replace(/~/g, ' LIKE ')
    .replace(/</g, '%')
    .replace(/>/g, '%')
    .replace(/#([\w,]*)/g, ' IN ($1)');
}
async function showTableLines (line, { connection }) {
    let list = line
    .replace(/\s,\s/g, ',')
    .replace(/\s=\s/g, '=')
    .replace(/\s~\s/g, '~')
    .replace(/\s\|\s/g, '|')
    .replace(/\s&\s/g, '&')
    .replace(/\s#\s/g, '#')
    .trim().split(/\s/).filter(o=>o);

    const table = list[0];
    if (!table) {
        this.error('invalid oper');
        this.prompt();
    }
    list = _.drop(list);
    let limit = _.last(list);
    if (+limit == limit) {
        list = _.dropRight(list);
    } else {
        limit = 1;
    }
    const fields = await formatFields(this, table, list[0], connection);
    const cond = formatCond(list[1]);
    await executeSQL(this, `SELECT ${fields} FROM ${table} ${cond} LIMIT ${limit}`, connection);
}
async function modifyTable(line, { connection }) {
    let list = line.replace(/\s,\s/g, ',').trim().split(/\s/);
    const table = list[0];
    let limit = _.last(list);
    if (typeof limit === 'number') {
        list = _.dropRight();
    } else {
        limit = 1;
    }

}
async function removeTable(line, { connection }) {
    let list = line.replace(/\s,\s/g, ',').trim().split(/\s/);
    const table = list[0];
    let limit = _.last(list);
    if (typeof limit === 'number') {
        list = _.dropRight();
    } else {
        limit = 1;
    }

}
async function copyTableRows(line, { connection }) {
    let list = line.replace(/\s,\s/g, ',').trim().split(/\s/);
    const table = list[0];
    let limit = _.last(list);
    if (typeof limit === 'number') {
        list = _.dropRight();
    } else {
        limit = 1;
    }

}
function togglePrettyShell() {
    _prettyShell = !_prettyShell;
    this.print('pretty format change to ' + _prettyShell);
    this.prompt();
}
function showHelp () {
    this.print('commands:', 'blue');
    this.print('    <h|help>: show help');
    this.print('    <q|exit>: exit');
    this.print('    ls(l): showTables|ls -: showDatabases|ls table: showTableFields');
    this.print('    s(show): showTableLines # s table f1,f2>,<f3> (f1=xx&f2=yy)|f3=zz|f4~<xx>|f5#1,2,3 limit');
    this.print('    m(modify): modifyTable');
    this.print('    r(remove): removeTable');
    this.print('    c(copy): copyTableRows');
    this.print('    _: togglePrettyShell');
    this.print('');
    this.prompt();
}
const COMMANDS = {
    'h|help': showHelp,
    'q|exit': function () { this.close() },
    'l|ls': showTables,
    's': showTableLines,
    'm': modifyTable,
    'r': removeTable,
    'c': copyTableRows,
    '-': togglePrettyShell,
    'default': executeLine,
};

createMysql(COMMANDS, { prompt: 'mysql', history: [ 's', 'm', 'r', 'c' ] });
