#!/bin/bash

source ~/command/common
ip="10.254.33.105"
password=longmaster
_oper=0

function pcs_restart()
{
	expect -c "
		spawn ssh root@$ip;
		expect {
			\"*password:\" {send \"$password\r\"; exp_continue}
			\"*#\" {send \" cd /server/pcs3\r killall pcs\r ./run_pcs.sh\r \"}
		}
		interact
	"
}

function pcs_restart_exit()
{
	expect -c "
		spawn ssh root@$ip;
		expect {
			\"*password:\" {send \"$password\r\"; exp_continue}
			\"*#\" {send \" cd /server/pcs3\r killall pcs\r ./run_pcs.sh\r exit\r \"}
		}
	"
}

function pcs_enter()
{
	expect -c "
		spawn ssh root@$ip;
		expect {
			\"*password:\" {send \"$password\r\"; exp_continue}
			\"*#\" {send \" cd /server/pcs3\r \"}
		}
		interact
	"
}

function show_help()
{
	local -a list
	list="xpcs"
	list=("${list[@]}" "Usage :xpcs [-r|-e|-h]")
	list=("${list[@]}" "pcs:login ssh and cd pcs dir")
	list=("${list[@]}" "pcs -r:restart pcs and stay in ssh")
	list=("${list[@]}" "pcs -e:restart pcs and exit ssh")
	list=("${list[@]}" "pcs -h:show help")
	__msgbox "${list[@]}"
}


function main()
{
	while getopts :reh opt;do
		case $opt in
			r)_oper=1;;
			e)_oper=2;;
			*)show_help;exit;;
		esac
	done
	case $_oper in
		0)pcs_enter;;
		1)pcs_restart;;
		2)pcs_restart_exit;;
	esac
}

main "$@"
