#!/usr/local/bin/node
const request = require('superagent');
const program = require('commander');

program
.version('0.0.1')
.option('-u, --url [http://127.0.0.1:3000/test]', 'url of api')
.option('-d, --data <json>', 'data must be json format', (v)=>eval('v='+v), {})
.parse(process.argv);

const { url, data } = program;

request
.post(url)
.set({
    'Accept': 'application/json',
    'Content-Type': 'application/json',
})
.send(data)
.end((error, res) => {
    if (error) {
        console.error('recv error:', error);
    } else {
        console.log(JSON.stringify(res.body, null, 2));
    }
});
