#!/usr/local/bin/node
var request = require('superagent');
var program = require('commander');

function post(url, param) {
    return new Promise((resolve, reject) => {
        const req = request
        .post(url)
        .set({
            'Accept': 'application/json',
            'Content-Type': 'application/json',
        })
        .send(param);

        req.end((error, res) => {
            if (error) {
                console.error('recv error:', error);
                reject();
            } else {
                resolve(res.text);
            }
        });
    });
}

program
.version('0.0.1')
.option('-u, --url [http://127.0.0.1:3000/test]', 'url of api')
.option('-d, --data <json>', 'data must be json format', (v)=>eval('v='+v), {})
.parse(process.argv);

let { url, data } = program;

var body = JSON.stringify(data);
post(url, data).then((result)=>{
    console.log("recv:", JSON.stringify(result, null, 2));
});
