#!/usr/bin/expect
set ip 10.254.33.105
set password longmaster
set dir /server/pns/demo
set task accessServer

spawn ssh root@$ip
expect "*password:"
send "$password\r"
expect "*#"
send "cd $dir\rkillall $task\r./$task\r"
expect eof
exit
