#!/usr/local/bin/node

var os = require('os');
var fs = require('fs');
var express = require('express');
var qrcode = require('./js/qrcode.js');

function getIPAdress() {
    var interfaces = os.networkInterfaces();
    for(var devName in interfaces){
        var iface = interfaces[devName];
        for(var i=0;i<iface.length;i++){
            var alias = iface[i];
            if(alias.family === 'IPv4' && alias.address !== '127.0.0.1' && !alias.internal){
                return alias.address;
            }
        }
    }
}

function startServer(port, file) {
    var server = app.listen(port);
    server.on('listening', function () {
        console.log(`http://${ip}:${port}`);
        if (typeof file !== 'undefined') {
            const url = `http://${ip}:${port}/${file}`;
            qrcode.showCode(url);
        }

        process.on('SIGINT', ()=>{
            if (typeof file !== 'undefined') {
                qrcode.resetScreen();
            }
             process.exit(0);
        })
    });
    server.on('error', function (err) {
        startServer(port+1, file);
    })
}

function createServerFile(filename) {
    code = 'var express = require("express");';
    code += '\nvar bodyParser = require("body-parser");';
    code += '\nvar fs = require("fs");';
    code += '\n';
    code += '\napp.use(express.static(__dirname + "/public"));';
    code += '\napp.use(bodyParser.urlencoded({ extended: false }));';
    code += '\napp.use(bodyParser.json());';
    code += '\napp.use(bodyParser.text());';
    code += '\n';
    code += '\napp.get("/test", (req, res)=>{';
    code += '\n    console.log(req.body);';
    code += '\n    res.send("hello");';
    code += '\n});';
    code += '\n';
    code += '\napp.listen(3000, function() {';
    code += '\n    console.log("server listen on: http://localhost:3000");';
    code += '\n});';
    fs.writeFileSync(filename, code);
}

var ip = getIPAdress();
var port = 3000;
var app = express();
app.use(express.static('.'));
app.get('/mz/*', function (req, res) {
    var img = req.url.replace('/mz/', '');
    var html = `
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            .img {
                width: 100%;
                height: 100%;
                position: absolute;
                left: 0;
                top: 0;
            }
        </style>
    </head>
    <body style='background:red;'>
        <img src='../${img}' class='img'>
    </body>
    </html>
    `;
    res.send(html);
});

var param = process.argv[2];
var param1 = process.argv[3];
if (param === '-h' || param === '--help') {
    console.log('');
    console.log('xserver opts');
    console.log('');
    console.log('   -h|--help: show help');
    console.log('   -c|--create: create a app.js file for nodejs server');
    console.log('   -i|--image [name]: show iphone6 size for image');
    console.log('   file: show download qrcode for file');
    console.log('');
} else if (param === '-c' || param === '--create') {
    createServerFile('app.js');
} else if (param === '-i' || param === '--image') {
    console.log('http:'+ip+':'+port+'//'+param1);
    startServer(port);
} else {
    startServer(port, param);
}
