#!/bin/bash

source ~/command/common
ip="localhost"
port=22
password=admin
_remote_root=/root/main/
_oper=0
_name=""
_localpath="./"
_remotepath="${_remote_root}"

function xssh_enter() {
	if type expect1 >/dev/null 2>&1; then
		expect1 -c "
		set timeout 30000;
		spawn ssh root@${ip} -p ${port};
		expect1 {
			\"*password:\" {send \"${password}\r\"; exp_continue}
			\"*#\" {send \" cd  ${_remote_root}\r\"}
		}
		interact
		"
	else
		echo "密码: ${password}"
		echo "命令: cd ${_remote_root}"
		echo ssh root@${ip} -p ${port}
		__setclipboard "${password}"
		ssh root@${ip} -p ${port}
	fi
}
function xssh_push() {
	[ -z "${_localpath}" ]&&return
	if type expect1 >/dev/null 2>&1; then
		expect1 -c "
		set timeout 30000;
		spawn scp -P ${port}  -r "${_localpath}" "root@${ip}:${_remotepath}"
		expect1 {
			\"*password:\" {send \"${password}\r\"}
		}
		interact
		"
	else
		echo "密码: ${password}"
		echo scp -P ${port}  -r "${_localpath}" "root@${ip}:${_remotepath}"
		__setclipboard "${password}"
		scp -P ${port}  -r "${_localpath}" "root@${ip}:${_remotepath}"
	fi
}
function xssh_pull() {
	[ -z "${_localpath}" ]&&return
	if type expect1 >/dev/null 2>&1; then
		expect1 -c "
		set timeout 30000;
		spawn scp -P ${port}  -r "root@${ip}:${_remotepath}" "${_localpath}"
		expect1 {
			\"*password:\" {send \"${password}\r\"}
		}
		interact
		"
	else
		echo "密码: ${password}"
		echo scp -P ${port}  -r "root@${ip}:${_remotepath}" "${_localpath}"
		__setclipboard "${password}"
		scp -P ${port}  -r "root@${ip}:${_remotepath}" "${_localpath}"
	fi
}
function show_help() {
	local -a list
	list="xssh"
	list=("${list[@]}" "Usage: xssh [-s|-l|-h]")
	list=("${list[@]}" "xssh: login ssh")
	list=("${list[@]}" "xssh -s [local:remote]: push local file/dir to ssh server")
	list=("${list[@]}" "xssh -l [remote:local]: pull remote file/dir from ssh server to local")
	list=("${list[@]}" "xssh -c [config file]: set config file")
	list=("${list[@]}" "xssh -h: show help")
	__msgbox "${list[@]}"
}
function main() {
	while getopts :s:l:c:p:o:atrh opt;do
		case ${opt} in
			s)_oper=1;_localpath="${OPTARG%%:*}";_remotepath="${OPTARG##*:}";;
			l)_oper=2;_remotepath="${OPTARG%%:*}";_localpath="${OPTARG##*:}";;
            a)_config_file="${HOME}/account/ali_yun_config";;
            t)_config_file="${HOME}/account/shen_ou_config";;
            r)_config_file="${HOME}/account/oracle_config";;
			c)_config_file="$OPTARG";;
			*)show_help;exit;;
		esac
	done
	if ! [ "${_localpath:0:1}" = "/" -o "${_localpath:0:1}" = "~" ];then
		_localpath="./${_localpath}"
	fi
	if ! [ "${_remotepath:0:1}" = "/" -o "${_remotepath:0:1}" = "~" ];then
		_remotepath="${_remote_root}${_remotepath}"
	fi

    if [ -n "${_config_file}" ];then
	    ip=`sed '/^public_ip=/!d;s/.*=//' ${_config_file}`
	    password=`sed '/^password=/!d;s/.*=//' ${_config_file}`
	    port=`sed '/^port=/!d;s/.*=//' ${_config_file}`
		if [ -z "${port}" ];then
			port=22
		fi
    fi

	case ${_oper} in
		0)xssh_enter;;
		1)xssh_push;;
		2)xssh_pull;;
	esac
}

main "$@"
