#!/bin/bash
source ~/command/common

_oper=0
_reg=""
_func=""

function genrate_param_from_model() {
    if __mac ;then
        pbpaste|sed 's#:.*//#, //#'|pbcopy
    else
         cat /dev/clipboard|sed 's#:.*//#, //#' > /dev/clipboard
    fi
}

function genrate_param_without_comment() {
    if __mac ;then
        pbpaste|sed 's#\s*//.*$##'|sed 's/.* //'|pbcopy
    else
         cat /dev/clipboard|sed 's#\s*//.*$##'|sed 's/.* //' > /dev/clipboard
    fi
}

function genrate_param_for_one() {
    if __mac ;then
        pbpaste|sed 's#,#: 1,#'|pbcopy
    else
         cat /dev/clipboard|sed 's#\s*//.*$##'|sed 's/.* //' > /dev/clipboard
    fi
}

function genrate_param_for_js() {
    if __mac ;then
        pbpaste|sed "s#\(\w\+\)[,]*\s*\(//.*\)#\1: '', \2#"|pbcopy
    else
         cat /dev/clipboard|sed "s#\(\w\+\)[,]*\s*\(//.*\)#\1: '', \2#" > /dev/clipboard
    fi
}

function change_english_symbol_to_chinese() {
    if __mac ;then
        pbpaste|sed "s#,#，#g"|sed "s#:#：#g"|sed "s#\.#。#g"|pbcopy
    else
         cat /dev/clipboard|sed "s#,#，#g"|sed "s#:#：#g"|sed "s#\.#。#g" > /dev/clipboard
    fi
}

function change_chinese_symbol_to_english() {
    if __mac ;then
        pbpaste|sed "s#，#,#g"|sed "s#：#:#g"|sed "s#。#.#g"|pbcopy
    else
         cat /dev/clipboard|sed "s#，#,#g"|sed "s#：#:#g"|sed "s#。#.#g" > /dev/clipboard
    fi
}

function getSubmitComments() {
    str=""
    while read line;do
        str="${str}\`${line}\`,"
    done
	node -e " \
    var list = [${str}]; \
    var ret = list.filter(o=>o).map(o=>{ \
        var m = o.match(/(.*)(${_reg})(.*)/); \
        var f = ${_func}; \
        return !m ? o : m[1] + (typeof(f) === 'function' ? f(m[2]) : +m[2] + f) + m[3]; \
    }); \
	console.log(ret.join('\n')); \
	"
}

function add_for_number() {
    _reg="${1%:*}"
    _func="${1#*:}"
    if [ "$_reg:$_func" != "$1" ];then
        echo "格式：xt -a reg:num|str|func"
        exit
    fi
    if __mac ;then
        pbpaste|getSubmitComments
    else
         cat /dev/clipboard|getSubmitComments > /dev/clipboard
    fi
}

function get_text_from_xml() {
    if __mac ;then
        pbpaste|sed "s#<[^>]*>##g"|pbcopy
    else
         cat /dev/clipboard|sed "s#<[^>]*>##g" > /dev/clipboard
    fi
}

function show_help()
{
	local -a list
	list="help"
	list=("${list[@]}" "Usage :xt [OPTIONS]")
	list=("${list[@]}" "  -m: 将model的字段变为函数的声明参数")
	list=("${list[@]}" "      @如: createTime: { type: Date }, // 创建时间 -> createTime, //创建时间")
	list=("${list[@]}" "  -p: 将函数的声明参数去除注释作为函数调用参数")
	list=("${list[@]}" "      @如: createTime, //创建时间 -> createTime,")
	list=("${list[@]}" "  -j: 将函数的声明参数添加参数空字符串作为调试参数")
	list=("${list[@]}" "      @如: createTime, //创建时间 -> createTime: '', //创建时间")
	list=("${list[@]}" "  -o: 将函数的声明参数添加参数数字1作为调试参数")
	list=("${list[@]}" "      @如: createTime, //创建时间 -> createTime: 1, //创建时间")
	list=("${list[@]}" "  -a: add num for regex match (reg:num|str|func, 注意\和=>需要转义成\\\\和=\>)")
	list=("${list[@]}" "  -t: 获取xml的文字部分")
	list=("${list[@]}" "  -c: 将英文的符号改变为中文的符号")
	list=("${list[@]}" "  -C: 将中文的符号改变为英文的符号")
	list=("${list[@]}" "  -h: 帮助")
	__msgbox "${list[@]}"
    exit
}

function main()
{
	local oper_right param
	oper_right=0

	if [ "$1" = "--help" ];then
		show_help
	fi

	while getopts :mpojta:cCh opt;do
		oper_right=1
		case $opt in
			m)_oper=1;;
			p)_oper=2;;
			o)_oper=3;;
			j)_oper=4;;
			a)_oper=5;param="$OPTARG";;
			t)_oper=6;;
			c)_oper=7;;
			C)_oper=8;;
			*)show_help;;
		esac
	done

	case $_oper in
        1)genrate_param_from_model;;
		2)genrate_param_without_comment;;
        3)genrate_param_for_one;;
        4)genrate_param_for_js;;
        5)add_for_number "${param}";;
        6)get_text_from_xml;;
        7)change_english_symbol_to_chinese;;
        8)change_chinese_symbol_to_english;;
        *)show_help;;
	esac
}

main "$@"
