#!/bin/bash
source ~/command/common

if __cygwin;then
    DIST=$WINDOWS_HOME
else
    DIST=$HOME
fi

if [ "$1" = "--help" -o  "$1" = "-h" ];then
  echo ./install [--es6]
  exit
fi
if __windows;then
    cp ./config/keymap_windows.cson $DIST/.atom/
else
    cp ./config/keymap.cson $DIST/.atom/
fi
cp ./config/config.cson $DIST/.atom/
cp ./config/snippets.cson $DIST/.atom/

if [ "$1" = "--es6" ];then
  cp "./config/react6.cson" "$DIST/.atom/packages/react/snippets/JavaScript (JSX).cson"
else
  cp "./config/react.cson" "$DIST/.atom/packages/react/snippets/JavaScript (JSX).cson"
fi
echo "done"
