#!/bin/bash
#############################################
# author:fang
# name  : install exvim
#############################################

src_path=$(pwd)
cd ~

if [ -a ~/.bashrc ];then
	echo backup .bashrc
	mv ~/.bashrc ~/.bashrc
fi

ln -s ${src_path}/.bashrc .bashrc
